### ISSUE TITLE
getting a crash with the Multi Mc build 1.4.1-0.4.7 build  

### ISSUE THREAD

**Issue by Dragonracer1973** [Boundarybreaker/Aquarius-Fabric#3]
[crash-2019-05-14_07.11.49-client.txt](https://github.com/Boundarybreaker/Aquarius-Fabric/files/3177581/crash-2019-05-14_07.11.49-client.txt)

**Comment by LemmaEOF** [comment]
The Aquarius version you are using is only for Minecraft 1.14.1. Mojang changed how block entities are registered in 1.14.1, so you should use [this version](https://minecraft.curseforge.com/projects/aquarius/files/2706767) instead. I noticed that I misnamed the 1.14.1 version on CurseForge, so that has now been fixed.

**Comment by Boundarybreaker** [comment]
The Aquarius version you are using is only for Minecraft 1.14.1. Mojang changed how block entities are registered in 1.14.1, so
