### ISSUE TITLE
[1.16.1] The player remains in the air after the Atlantean effect ends

### ISSUE THREAD

**Issue by allanf181** [Boundarybreaker/Aquarius-Fabric#6]
@JSJBDEV (issues are disabled on fork)

On server the player is kicked for flying when that happens

**Comment by JSJBDEV** [comment]
Hm.... I'll have to look into that, does the effect end because you leave the conduit area? if so I am somewhat doubtful about making the player "not fly" fast enough a fix for a server could be to turn flying on in config and might end up being the only really way of fixing it, but I'll do some testing this weekend

**Comment by allanf181** [comment]
I think the problem is that gravity is still disabled when the effect ends

**Comment by JSJBDEV** [comment]
potentially, looking at a fix now

**Comment by JSJBDEV** [comment]
ok I found a fix to it kicking you when you run out of the effect, but you may still occasionally get kicked with the effect, but you can go right back to using it after, @Boundarybreaker you can close this issue now cuz I cant, and ill try open issues on my branch
